### ISSUE TITLE
Fan Duct AirFlow Direction

### ISSUE THREAD

**Issue by Ramrawd** [thrutheframe/Tiki3#3]
Hi there, I love your design and I've been using it for a few weeks now, but my one issue with it is the part cooling fan blows more air behind my nozzle rather than right at it. I've noticed my overhang and bridging quality has decreased since moving to this design. This is in comparison to the 5015 single blower petsfang duct system. The petsfang blows air almost directly from the sides. 

If the fan duct tips extended out a bit further I think that would help in directing the airflow inwards towards the extruder nozzle.

I've attached a picture of a very rough mockup I made in Tinkercad. Unfortunately, my cad skills are limited to Tinkercad at the moment so I'd have no idea where to even start with such complicated shapes. 

![Screenshot 2021-10-10 172719](https://user-images.githubusercontent.com/48835880/136716324-6c2b5d7a-7142-44e4-8032-bc7f9cbc58d8.png)

Any thoughts on your experiences with the ducts and potentially extending them/changing their angle?

Thanks!

**Comment by thrutheframe** [comment]
hi, thanks for the feedback, I double checked. your observation is correct. the airflow speed at the back of the nozzle is faster than that of the front. This is an oversight on my design where airflow around a gentle curve has less resistance than the tighter one. 

While I workout a revision of the design, could you help test an idea? can you install a 2mm washer between the duct and the body to bring the fan duct forward so that the airflow is point at the nozzle. thanks

**Comment by Ramrawd** [comment]
Thanks for taking a look at this! 

Here are pictures with the 2mm spacer added. Still hitting a bit behind the nozzle even with the spacers

![IMG_20211010_231507](https://user-images.githubusercontent.com/48835880/136737118-290ec239-0ad1-4bdc-8be0-ff6570bf952f.jpg)

![IMG_20211010_231807](https://user-images.githubusercontent.com/48835880/136737119-22bfb433-7b4f-45d3-aba1-4f2fb5cfe9c9.jpg)

Here's one more photo that captures where the airflow is (Note this is with the 2mm spacer):

![IMG_20211010_232519](https://user-images.githubusercontent.com/48835880/136737685-8fdbe82c-450f-47ac-bfa8-f142594d4dac.jpg)

**Comment by thrutheframe** [comment]
thanks for the test and images. I will rework the angle of the duct.

**Comment by thrutheframe** [comment]
![Screenshot 2](https://user-images.githubusercontent.com/68491566/136955489-d3aa0e62-9ba3-495a-9f92-a4b06b0adc77.png)
![Screenshot 3](https://user-images.githubusercontent.com/68491566/136955502-0c885a3b-eb7b-4a3a-8bff-f8578349db37.png)
![Screenshot 4](https://user-images.githubusercontent.com/68491566/136955515-0bc423d4-98b5-40d3-8f3b-7b9ffecd2726.png)

**Comment by thrutheframe** [comment]
I reworked the fan duct design to focus the air just under the nozzle and a clean exit to the back.

**Comment by Ramrawd** [comment]
Would it be possible to move the airflow further forward in relation to the nozzle? 

It appears the the biggest volume of airflow is still intercepting behind the nozzle. 

Also, from my own curiosity, what software are you using to model the airflow and design these parts? It really looks impressive. 

Thanks!

**Comment by thrutheframe** [comment]
![Screenshot 1](https://user-images.githubusercontent.com/68491566/137066797-cddd96fb-4161-4009-873a-aa836c7c6541.png)
![Screenshot 2](https://user-images.githubusercontent.com/68491566/137066801-10d3b499-5e08-4e25-bd92-83b99388fea3.png)
![Screenshot 3](https://user-images.githubusercontent.com/68491566/137066802-0dc9d65a-b6a6-49c1-a3cc-a85205f5bdff.png)

**Comment by thrutheframe** [comment]
I moved the airflow forward by 2mm and out of curiosity added a calibration cube to simulate how the airflow looked. very interesting... 

I use SimScale to model the cfd. I am still very much a beginner with this cloud based application. so this simulation is a rough idea of how the airflow moves.

**Comment by Ramrawd** [comment]
Hmm interesting dynamic with the cube in the way. 

Do you happen to have the STL for printing/testing? I could get one on the printer tonight and test it out tomorrow. 

I'm going to checkout SimScale looks like fun honestly.

**Comment by thrutheframe** [comment]
The design should be ready in 2-3 days for test prints. Will be good if u can help me test out too. I am currently tweaking it to optimise for printing. Will be updating tiki3 along with a new body_top with adxl mount for klipper users.

**Comment by Ramrawd** [comment]
Sounds great! I'll keep an eye out for it. Also what an awesome addition with the ADXL mount. 

I ended up using an m3 screw in the empty screw hole next to the cable relief mount to mount my adxl. Ended up working well since the threads held in the petg. That said a dedicated location for the ADXL is a welcome addition! 

Thanks again for all your hard work
![IMG_20211012_233559](https://user-images.githubusercontent.com/48835880/137073397-75c8ceac-9548-49ec-87e5-9cb31ec7673b.jpg)
!
![IMG_20211012_233545](https://user-images.githubusercontent.com/48835880/137073412-018281ab-82cb-427e-8541-b01ff5bb53a2.jpg)

**Comment by thrutheframe** [comment]
"3_2 fan_duct V2.stl" and "M3 3_2 body_top adxl.stl" uploaded for testing.  Do note that the adxl mount will only work with the fan_duct V2

I have tune the design to be able to print without support with overhang not more than 50 degree.

**Comment by Ramrawd** [comment]
Thanks for the uploads. I'll throw it on the printer now and see how it comes out. 

Gonna need to solder some new connectors on the adxl to utilize the new mount location.

**Comment by Ramrawd** [comment]
New fan position looks pretty good! Also, please excuse the print quality on the duct... trying out a new filament and don't have my settings  dialed in yet :) 

Haven't had a chance to resolder my ADXL but there's a good amount of clearance to squeeze it in with the 90 deg pins. 

![IMG_20211015_115522](https://user-images.githubusercontent.com/48835880/137532213-25be491c-dbe0-4a59-9807-826fac08bf2c.jpg)

![IMG_20211015_115424](https://user-images.githubusercontent.com/48835880/137532217-551f1b61-893c-438b-bc3d-f79017a3c463.jpg)

**Comment by thrutheframe** [comment]
thanks for the feedback. In my testing, the airduct works better with improved overhangs. Will consider issue resolved and be closing this thread.
