### ISSUE TITLE
Removing duct support tip

### ISSUE THREAD

**Issue by marcfon** [thrutheframe/Tiki3#4]
I broke one duct while removing the supports. The mistake I made was to start removing it from the bottom with cutters. 

On my second print I found that it's much easier when you just insert a small flat screwdriver in the gap between support and duct and lift the support a little. That makes them break off cleanly without risking breaking the duct. This might be helpful to add in the documentation.

Thanks a lot for this project!

**Comment by thrutheframe** [comment]
thanks for the suggestion. Will add in a description.
