### ISSUE TITLE
NF Zone fitting issue

### ISSUE THREAD

**Issue by marcfon** [thrutheframe/Tiki3#5]
I'm encountering an issue where the head of the [NF Zone V6](https://www.aliexpress.com/item/1005001648634333.html) hot end isn't fitting the back plate.

The gap in the head is 5.8mm while the backplate bar is 7.0mm thick.

![The example](https://i.imgur.com/EVDcRPr.jpg)

**Comment by thrutheframe** [comment]
Tiki3 was design for NF-Zone CR10 version. The V6 version will not be able to fit. I have upload the step files of the body, which you can do some remix to allow a V6 adapter to fit. thanks

**Comment by marcfon** [comment]
Ah shoot I didn't realize that there would be much difference between the V6 and the CR10 version. I see that it's described in the FAQ, missed that line apparently. 

Would you expect that many changes would be needed to make it compatible with a V6 style hot end or just the backplate?
