### ISSUE TITLE
Idea - screw hole to access heatsink screws

### ISSUE THREAD

**Issue by pankleks** [thrutheframe/Tiki3#6]
Hello!

First of all awesome work - I just installed it - and looking forward to see performance.

One idea - in body top - there could be a 2 holes in areas to access heatsink mounting screws + hole for tiny screw to block heartbreak.

I don't think it would affect part structural strength but it would allow to access these screw (for inspection/tightening) without unmounting entire part.

Let me know what you think:)

**Comment by thrutheframe** [comment]
in one of the first few prototype, I added the 2 holes (4mm) for accessing the heatsink. I got sporadic soft whistling sound when the fan start running. I have added the step files of the body. U may want to try it out by adding the holes.  

Structurally there should be no issue with holes added.

**Comment by pankleks** [comment]
thanks!
