### ISSUE TITLE
No Fan duct in step file ?

### ISSUE THREAD

**Issue by yduf** [thrutheframe/Tiki3#8]
Hello there,

First thank you very much for providing a step file.
It helps me a a lot to play with it and remix the part.

A quick question: I am loading it with Freecad, but I don't see the fan-duct part in the step file ?
(while I see both fans). Is it normal ?

As I am just flipping 180° the orbiter, I don't need really need it. It is just that to have the final look in cad software, it is better since step files are rendered much better than stl in freecad.

Regards,

Yves

**Comment by thrutheframe** [comment]
The step file only has the body and bl bracket for others to remix for different printer. The fanduct was omitted from the step file. Only stl available.
