### ISSUE TITLE
Top part?

### ISSUE THREAD

**Issue by Arakon** [thrutheframe/Tiki3#9]
Is the top part that extends above the original X-Carriage necessary for operation/stability, other than mounting the cable guide? I use a titan extruder that is mounted on a printed plate from the back, which would most likely collide with that extension.

**Comment by thrutheframe** [comment]
it is meant for cable guide and any other things that users might want to mount. Other thatn that it does not affects operations and stability.

**Comment by Arakon** [comment]
Thank you.
